### ISSUE TITLE
Problem with some instructions of bookmark addon

### ISSUE THREAD

**Issue by Illegit** [lilive/Freeplane-Bookmarks-add-on#1]
Hi lilive, here below some errors in FP 1.8.1 6 java 1.8.0 202, w10
![image](https://user-images.githubusercontent.com/62674157/77592348-43642900-6ef2-11ea-9624-22f4c4bd1308.png)
this the message if activating the toggle command
![image](https://user-images.githubusercontent.com/62674157/77592441-773f4e80-6ef2-11ea-863f-af67c7794b27.png)
and this message if activating the jump to command

for the log file please have a look to the bug  2752 in Freeplane.
Thanks
KR
SFPC

**Comment by lilive** [comment]
This seems to be fixed now.
