### ISSUE TITLE
Error with installation

### ISSUE THREAD

**Issue by ArturGudiev** [lilive/Freeplane-Bookmarks-add-on#2]
I tried to install the add-on by opening bookmarks.addon.mm. 

But I got error 
Error on installation: org.freeplane.plugin.script.ExecuteScriptException: BUG! exception in phase 'semantic analysis' in source unit 'Script1.groovy' Unsupported class file major version 57

**Comment by lilive** [comment]
This error seems to be relative to your java version. Can you update java and try again ?

**Comment by lilive** [comment]
No response, I close the issue.
