### ISSUE TITLE
Retour d’expérience

### ISSUE THREAD

**Issue by bepolymathe** [lilive/Freeplane-Bookmarks-add-on#3]
Salut, 

Je vais écrire un message en français sur github ça va me changer un peu ;-) 
Merci pour cet add-on très utile. 
Un cas d’usage peu pratique. Si tu copies un noeud et que tu colles un clone dans un autre endroit de la carte... tu obtiens deux les deux noeuds comme résultats dans la recherche de marque-page. C’est logique mais il serait peut-être plus utile, en cas de noeud identifique, d’entourer les résultats correspondants...
Qu’en dis-tu ?
Bonne soirée.

**Comment by lilive** [comment]
> Je vais écrire un message en français sur github ça va me changer un peu ;-)

C'est pas faux !

Merci pour le retour. Qu'imagines-tu quand tu écris "entourer les résultats correspondants" ?

**Comment by bepolymathe** [comment]
Salut, 

En fait, je voulais dire qu’il serait peut-être une bonne idée, en cas de noeud clonés, de n’en afficher qu’un dans les résultats de recherches des marques pages et d’afficher visuellement avec l’option "filtrer les noeuds sélectionnés" 
![image](https://user-images.githubusercontent.com/29939805/97117294-f869f880-1702-11eb-8c64-3077ce28963c.png)

**Comment by lilive** [comment]
Salut bepolymathe,
Voilà j'ai fait au plus simple (pour moi). Les explications apparaissent avec l'icône (?) au-dessus des marque-pages standards. C'est dans la v0.7.1, publiée à l'instant. J'espère que ça t'ira.

**Comment by bepolymathe** [comment]
Salut, 

Je viens d’essayer. C’est parfait comme ça. Merci bien. 
Belles fêtes à toi (malgré le contexte).
