### ISSUE TITLE
Feature Request: Clean bookmarks in branch

### ISSUE THREAD

**Issue by EdoFro** [lilive/Freeplane-Bookmarks-add-on#4]
Hi lilive,
Like I wrote in the Freeplane forum ([here](https://sourceforge.net/p/freeplane/discussion/758437/thread/ec280c4e/?page=1&limit=25#b789)), I had an Idea about a feature request and thought I may post it here too.

I think you may add a command that

**cleans all bookmarks in branch** under the selected node.

- this way you can add bookmarks when working on a task and reset them for the next one.
- I think it should have a confirmation dialog.
- Maybe with a dialog option to choose which type of bookmarks do you want to clean (named, unnamed or all of them)

just an idea.
Thanks!
edo

**Comment by lilive** [comment]
Hi Edo,
Done in v0.7.1

**Comment by EdoFro** [comment]
Thanks!!
