### ISSUE TITLE
FP 1.9.1 has a bug that affects your addon

### ISSUE THREAD

**Issue by EdoFro** [lilive/Freeplane-Bookmarks-add-on#5]
Hi lilive,
Just for your information:
I reported a bug in Freeplane that deletes the map storage variables when copying styles from another map.
More information here: [bug report 2934](https://sourceforge.net/p/freeplane/bugs/2934/)

I think you use these type of variables in Bookmarks and/or Jumper addon.

Best regards,
edo

**Comment by lilive** [comment]
Thank you Edo !
You're right, the bookmark add-on use the map storage (Jumper do not).
BTW, I do not write markdown documents so much, but I'm enjoying to follow your add-on development.
So long !

**Comment by EdoFro** [comment]
You're welcome!
I really don't write markdown documents neither, just the ones needed for Github, but I was entertained by doing that addon. My only problem is the documentation. It takes me more time than the coding!!
bye

**Comment by lilive** [comment]
HaHa ! I'm glad to offer you this caricature:
"I'm creating an add-on. I don't need it at all, except that it helps me a lot in the painful process to write the documentation about it."
:-p

Joke aside, I really understand the entertainment to code. I do this kind of things myself. And your add-on will benefit to others.

**Comment by EdoFro** [comment]
hahahaha, it's just like that!! ;)
